### ISSUE TITLE
Nieuwe aanbieder

### ISSUE THREAD

**Issue by Dp208** [gokgeld-terug/gokgeld-terug.github.io#1]
### Wat wil je wijzigen?

Home

### Wat is de wijziging?

Nieuwe aanbieder Dynamiet Nederland.

### Waarom wil je het wijzigen?

De consument heeft meer te kiezen. Wij rekenen slechts 33% en schakelen snel. 

### Wat is de onderbouwing van de wijziging? (vermeld bron artikelen)

https://www.dynamietnederland.nl/casino-claim-geld-terug/

**Comment by gokgeld-terug** [comment]
@Dp208 Geodendag, ik zal deze aanbieder toevoegen. Kan je me de volgende informatie geven:
- Betreft dit een massaclaim of individuele zaken?
- Vragen ze de speelgeschiedenis op, of moet de klant dat zelf aanleveren?

**Comment by Dp208** [comment]
Geachte heer, mevrouw,
Dank voor uw bericht en fijn dat u ons ook als aanbieder wil toevoegen.
Op dit moment behandelen wij uitsluitend individuele zaken.
Van cliënten hebben wij vernomen dat kantoren zoals Loonstein en Goldenstein alleen zaken aannemen waarbij consumenten minimaal €50.000 hebben verloren bij één specifiek casino. Bij Dynamiet Nederland starten wij echter procedures vanaf €5.000 bij de kantonrechter.
Onze kracht ligt in onze snelheid en efficiëntie. Wij zijn proactief en schakelen snel. Verder werken wij niet met externe procesfinanciers; wij financieren de gehele procedure zelf en dragen ook het volledige financiële risico. Voor onze diensten rekenen wij een commissie van 33%.
Cliënten krijgen bij ons een eigen advocaat of jurist toegewezen, wat zorgt voor directe bereikbaarheid en duidelijke communicatie over de voortgang van de zaak.
Daarnaast nemen wij zelf het initiatief om de transactiehistorie bij de betrokken casino's op te vragen.
Mocht u verdere vragen hebben, verneem ik dat graag.

Met vriendelijke groet,

***@***.***

Deepak Thakoerdien
Directeur

Dynamiet Nederland
J.L. van Rijweg 127, 2713 HZ, Zoetermeer

079 82 00 263
06 36 14 39 47

***@***.******@***.***>
www.dynamiet.nl<http://www.dynamiet.nl/>




Dit e-mail bericht is alleen bestemd voor de geadresseerde(n). Gebruik door andere is niet toegestaan. Indien u niet de geadresseerde(n) bent wordt u verzocht de verzender hiervan op de hoogte te stellen en het bericht te verwijderen.



Van: gokgeld-terug ***@***.***>
Verzonden: maandag 23 september 2024 17:47
Aan: gokgeld-terug/gokgeld-terug.github.io ***@***.***>
CC: Deepak Thakoerdien | Dynamiet Nederland ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [gokgeld-terug/gokgeld-terug.github.io] Nieuwe aanbieder (Issue #1)


@Dp208<https://github.com/Dp208> Geodendag, ik zal deze aanbieder toevoegen. Kan je me de volgende informatie geven:

  *   Betreft dit een massaclaim of individuele zaken?
  *   Vragen ze de speelgeschiedenis op, of moet de klant dat zelf aanleveren?

**Comment by gokgeld-terug** [comment]
Toegevoegd

**Comment by Dp208** [comment]
Hartelijk dank.

Met vriendelijke groet,

***@***.***

Deepak Thakoerdien
Directeur

Dynamiet Nederland
J.L. van Rijweg 127, 2713 HZ, Zoetermeer

079 82 00 263
06 36 14 39 47

***@***.******@***.***>
www.dynamiet.nl<http://www.dynamiet.nl/>




Dit e-mail bericht is alleen bestemd voor de geadresseerde(n). Gebruik door andere is niet toegestaan. Indien u niet de geadresseerde(n) bent wordt u verzocht de verzender hiervan op de hoogte te stellen en het bericht te verwijderen.



Van: gokgeld-terug ***@***.***>
Verzonden: dinsdag 24 september 2024 14:09
Aan: gokgeld-terug/gokgeld-terug.github.io ***@***.***>
CC: Deepak Thakoerdien | Dynamiet Nederland ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [gokgeld-terug/gokgeld-terug.github.io] Nieuwe aanbieder (Issue #1)


Toegevoegd

**Comment by Dp208** [comment]
Geachte heer, mevrouw,
Vanwege het grote aantal aanvragen en de omvang van de markt, hebben wij besloten om naast individuele procedures ook collectieve procedures op te starten. Ons tarief bedraagt 33%.
De eerste individuele rechtszaken zijn momenteel in behandeling bij zowel de kantonrechter als de civiele rechter. Wordt vervolgd.
Kunt u de nieuwe info op de site vermelden?

Met vriendelijke groet,

***@***.***

Deepak Thakoerdien
Directeur

Dynamiet Nederland
J.L. van Rijweg 127, 2713 HZ, Zoetermeer

079 82 00 263
06 36 14 39 47

***@***.******@***.***>
www.dynamiet.nl<http://www.dynamiet.nl/>




Dit e-mail bericht is alleen bestemd voor de geadresseerde(n). Gebruik door andere is niet toegestaan. Indien u niet de geadresseerde(n) bent wordt u verzocht de verzender hiervan op de hoogte te stellen en het bericht te verwijderen.



Van: Deepak Thakoerdien | Dynamiet Nederland
Verzonden: dinsdag 24 september 2024 14:37
Aan: 'gokgeld-terug/gokgeld-terug.github.io' ***@***.***>; gokgeld-terug/gokgeld-terug.github.io ***@***.***>
CC: Mention ***@***.***>
Onderwerp: RE: [gokgeld-terug/gokgeld-terug.github.io] Nieuwe aanbieder (Issue #1)

Hartelijk dank.

Met vriendelijke groet,

***@***.***

Deepak Thakoerdien
Directeur

Dynamiet Nederland
J.L. van Rijweg 127, 2713 HZ, Zoetermeer

079 82 00 263
06 36 14 39 47

***@***.******@***.***>
www.dynamiet.nl<http://www.dynamiet.nl/>




Dit e-mail bericht is alleen bestemd voor de geadresseerde(n). Gebruik door andere is niet toegestaan. Indien u niet de geadresseerde(n) bent wordt u verzocht de verzender hiervan op de hoogte te stellen en het bericht te verwijderen.



Van: gokgeld-terug ***@***.******@***.***>>
Verzonden: dinsdag 24 september 2024 14:09
Aan: gokgeld-terug/gokgeld-terug.github.io ***@***.******@***.***>>
CC: Deepak Thakoerdien | Dynamiet Nederland ***@***.******@***.***>>; Mention ***@***.******@***.***>>
Onderwerp: Re: [gokgeld-terug/gokgeld-terug.github.io] Nieuwe aanbieder (Issue #1)


Toegevoegd
